{
    "name": "HR Recruitment Automation",
    "version": "18.0.1.0.0",
    "summary": "Recruitment to employee automation with contracts, documents, leave and HR controls",
    "category": "Human Resources/Recruitment",
    "author": "QLK",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "portal",
        "web",
        "hr",
        "hr_recruitment",
        "hr_contract",
        "hr_holidays",
        "hr_attendance",
        "qlk_management",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/leave_data.xml",
        "data/mail_templates.xml",
        "data/hr_automation_cron.xml",
        "wizard/hr_applicant_reject_wizard_views.xml",
        "wizard/hr_applicant_employee_wizard_views.xml",
        "report/job_offer_template.xml",
        "report/job_offer_report.xml",
        "data/job_offer_mail_template.xml",
        "views/hr_applicant_views.xml",
        "views/hr_applicant_job_offer_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_leave_views.xml",
        "views/recruitment_document_views.xml",
        "views/biometric_device_views.xml",
    ],
    "installable": True,
    "application": False,
}
