# -*- coding: utf-8 -*-
{
    "name": "QLaw Engagement Letters",
    "summary": "Manage engagement letters for Al Hadhri Law Firm with dynamic contract controls.",
    "version": "1.0.0",
    "category": "Law",
    "license": "LGPL-3",
    "author": "Qlink Software",
    "website": "http://www.qlinksoftware.com",
    "depends": [
        "base",
        "mail",
        "contacts",
        "account",
        "hr",
        "qlk_law",
    ],
    "data": [
        "security/engagement_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/proposal_sequence.xml",
        "data/client_code_sequence.xml",
        "data/article_template.xml",
        "data/mail_template.xml",
        "data/cron_data.xml",
        "views/res_company_views.xml",
        "views/proposal_pricing_view.xml",
        "views/proposal_initiation_view.xml",
        "views/business_proposal_view.xml",
        "views/proposal_report_view.xml",
        "views/engagement_letter_views.xml",
        "views/engagement_proposal_views.xml",
        "views/cost_calculation_views.xml",
        "views/engagement_letter_menu.xml",
        "report/business_proposal_report.xml",
        "report/engagement_letter_report.xml",
        "report/engagement_letter_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "qlk_proposals_engagement_letter/static/src/scss/engagement_letter.scss",
        ],
    },
    "installable": True,
    "application": False,
    "sequence": 25,
}
